export const CREATE_TODO_INITIATE = 'CREATE_TODO_INITIATE'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const CREATE_TODO_FAIL = 'CREATE_TODO_FAIL'

export const GETALL_TODO_SUCCESS = "GETALL_TODO_SUCCESS"
export const GETALL_TODO_FAIL = "GETALL_TODO_FAIL"

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAIL = "DELETE_TODO_FAIL"